name = "VisualStructures"
uuid = "4ff8b045-ea8a-4ad0-a12a-3d0ba4e7e6b4"
authors = ["Petr Krysl <pkrysl@ucsd.edu>"]
version = "0.1.5"

[deps]
FinEtools = "91bb5406-6c9a-523d-811d-0644c4229550"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FinEtools = "^8"
JSON = "^0.21"
PlotlyJS = "^0.18"
julia = "^1.11"
